import { IOrderDetailResponse } from "../orderDetailsTracking.interface";

export let mockorderDetailsData: IOrderDetailResponse = {
  orderNumber: "123",
  patientFirstName: "",
  patientLastName: "",
  salesRepName: "",
  orderDate: "12-MAR-2021",
  salesRepPhone: "",
  salesRepEmail: "",
  csrName: "",
  csrPhone: "",
  csrEmail: "",
  trackingLink: "",
  trackingNumber: "",
  receivedFlag: "",
  releaseToShipFlag: "",
  releaseDate: "12-MAR-2021",
  validatedFlag: "",
  benefitsComplDate: "12-MAR-2021",
  therapyFlag: "",
  therapyDate: undefined,
  deliveredDate: "12-MAR-2021",
  deliveredFlag: "",
  rentalProduct: "",
  outForDeliveryFlag: "",
  outDeliveryDate: "12-MAR-2021",
  deliverySiteType: "",
};
