import {
  IAlertTypes,
  ISeverityTypes,
  IPatientAlert,
} from "../components/myPatients/patient.interface";

export const patientAlertList: IPatientAlert[] = [
  {
    alertID: "AL01",
    alertName: "Missing Rx",
    alertSubLabel: "",
    alertDate: null,
    alertType: IAlertTypes.MISRX,
    severity: null,
  },
  {
    alertID: "AL02",
    alertName: "Measurements Due",
    alertSubLabel: "For Jan 21-Jan 28",
    alertDate: null,
    alertType: IAlertTypes.MSDUE,
    severity: ISeverityTypes.MEDIUM,
  },
  {
    alertID: "AL03",
    alertName: "Pending Supply Order",
    alertSubLabel: "Excessive Supply",
    alertDate: null,
    alertType: IAlertTypes.PNDSO,
    severity: null,
  },
  {
    alertID: "AL04",
    alertName: "Measurements Due",
    alertSubLabel: "For Jan 21-Jan 28",
    alertDate: null,
    alertType: IAlertTypes.MSDUE,
    severity: ISeverityTypes.LOW,
  },
  {
    alertID: "AL05",
    alertName: "Supplies Delivered",
    alertSubLabel: "",
    alertDate: new Date("2022-03-14"),
    alertType: IAlertTypes.SUPDE,
    severity: null,
  },
  {
    alertID: "AL06",
    alertName: "Missing Docs",
    alertSubLabel: "",
    alertDate: null,
    alertType: IAlertTypes.MSDOC,
    severity: null,
  },
  {
    alertID: "AL07",
    alertName: "Measurements Due",
    alertSubLabel: "For Jun 21-Jun 28",
    alertDate: null,
    alertType: IAlertTypes.MSDUE,
    severity: ISeverityTypes.LOW,
  },
  {
    alertID: "AL08",
    alertName: "Discharge Pending",
    alertSubLabel: "",
    alertDate: null,
    alertType: IAlertTypes.DISPEN,
    severity: null,
  },
  {
    alertID: "AL09",
    alertName: "Shared Order",
    alertSubLabel: "From Jenny Kale",
    alertDate: null,
    alertType: IAlertTypes.SHODR,
    severity: null,
  },
  {
    alertID: "AL10",
    alertName: "Proof of Delivery Needed",
    alertSubLabel: "",
    alertDate: null,
    alertType: IAlertTypes.PODEL,
    severity: null,
  },
  {
    alertID: "AL11",
    alertName: "Confirm Placement",
    alertSubLabel: "",
    alertDate: null,
    alertType: IAlertTypes.CONPL,
    severity: null,
  },
  {
    alertID: "AL12",
    alertName: "Measurements Due",
    alertSubLabel: "Measurements due Today",
    alertDate: null,
    alertType: IAlertTypes.MSDUE,
    severity: ISeverityTypes.HIGH,
  },
  {
    alertID: "AL13",
    alertName: "Supplies Delivered",
    alertSubLabel: "",
    alertDate: new Date("2022-03-14"),
    alertType: IAlertTypes.SUPDE,
    severity: null,
  },
];
