import {
  IWoundAssesments,
  IWoundAssesmentsMap,
  IWoundDetail,
} from "../components/myPatients/patientAndTherapyDetails/orderOverview/orderOverview.interface";
import {
  WoundDetails,
  WoundListDetail,
} from "../components/myPatients/patientAndTherapyDetails/orderOverviewWoundProgressTab/WoundProgressTab.interface";

export const woundListMock: WoundListDetail = {
  id: 7360173,
  type: "Pressure Ulcer - Stage IV",
  location: "Pressure Ulcer - Stage IV",
  orientation: "Coccyx",
  direction: "Buttock",
  length: 1.8,
  width: 0.8,
  depth: 1.8,
  evaluationDate: "2018-04-24T00:00:00",
  therapyHoldDate: "2018-04-24T00:00:00",
  therapyResumptionDate: "2018-04-24T00:00:00",
};
export const woundDetails: WoundDetails = {
  wounds: [
    {
      id: 7360173,
      type: "Pressure Ulcer - Stage IV",
      location: "Pressure Ulcer - Stage IV",
      orientation: "Coccyx",
      direction: "Buttock",
      length: 1.8,
      width: 0.8,
      depth: 1.8,
      evaluationDate: "2018-04-24T00:00:00",
      therapyHoldDate: "2018-04-24T00:00:00",
      therapyResumptionDate: "2018-04-24T00:00:00",
    },
  ],
};
export const wooundDetailsTab: IWoundAssesments = {
  boneExposed: "",
  color: "",
  assessmentType: "",
  comorbidities: [],
  cycleDateRangeFrom: "",
  cycleDateRangeTo: "",
  debridementDate: "",
  debridementDone: "",
  debridementType: "",
  evaluationDate: "",
  exudateAppearance: "",
  holdVacTherapyDate: "",
  images: [],
  isEschar: "",
  isTherapyInUSe: "",
  isTunnelingPresent: "",
  isUnderMiningPresent: "",
  muscelExposed: "",
  otherComorbidities: "",
  status: "",
  subcutaneousTissueExposed: "",
  tissueExposed: "",
  tunnelingLength1: "",
  tunnelingLength2: "",
  tunnelingLocation1: "",
  tunnelingLocation2: "",
  underMiningLocation1From: "",
  underMiningLocation1Size: "",
  underMiningLocation1To: "",
  underMiningLocation2From: "",
  underMiningLocation2Size: "",
  underMiningLocation2To: "",
  volume: "",
  volumeDifference: 0,
  woundDepth: "",
  woundDescriptionBeefyRed: "",
  woundDescriptionBlackEschar: "",
  woundDescriptionDullPink: "",
  woundExudate: "",
  woundLength: "",
  woundWidth: "",
  woundDescriptionWhite: "",
};
export const woundAsesmentDetails: IWoundDetail = {
  assessments: ([] = [
    {
      volume: "",
      evaluationDate: "2023-05-15T00:00:00",
      status: "",
      color: "",
      volumeDifference: -6,
      assessmentType: "MWP",
      boneExposed: "",
      comorbidities: [],
      cycleDateRangeFrom: "",
      cycleDateRangeTo: "",
      debridementDate: "",
      debridementDone: "",
      debridementType: "",
      exudateAppearance: "",
      holdVacTherapyDate: "",
      isEschar: "",
      isTherapyInUSe: "",
      isTunnelingPresent: "",
      isUnderMiningPresent: "",
      muscelExposed: "",
      otherComorbidities: "",
      subcutaneousTissueExposed: "",
      tissueExposed: "",
      tunnelingLength1: "",
      tunnelingLength2: "",
      tunnelingLocation1: "",
      tunnelingLocation2: "",
      underMiningLocation1From: "",
      underMiningLocation1Size: "",
      underMiningLocation1To: "",
      underMiningLocation2From: "",
      underMiningLocation2Size: "",
      underMiningLocation2To: "",
      woundDepth: "",
      woundDescriptionBeefyRed: "",
      woundDescriptionBlackEschar: "",
      woundDescriptionDullPink: "",
      woundDescriptionWhite: "",
      woundExudate: "",
      woundLength: "",
      woundWidth: "",
    },
    {
      volume: "73",
      evaluationDate: "2023-04-17T00:00:00",
      status: "",
      color: "",
      assessmentType: "MWP",
      volumeDifference: -6,
      boneExposed: "",
      comorbidities: [],
      cycleDateRangeFrom: "",
      cycleDateRangeTo: "",
      debridementDate: "",
      debridementDone: "",
      debridementType: "",
      exudateAppearance: "",
      holdVacTherapyDate: "",
      isEschar: "",
      isTherapyInUSe: "",
      isTunnelingPresent: "",
      isUnderMiningPresent: "",
      muscelExposed: "",
      otherComorbidities: "",
      subcutaneousTissueExposed: "",
      tissueExposed: "",
      tunnelingLength1: "",
      tunnelingLength2: "",
      tunnelingLocation1: "",
      tunnelingLocation2: "",
      underMiningLocation1From: "",
      underMiningLocation1Size: "",
      underMiningLocation1To: "",
      underMiningLocation2From: "",
      underMiningLocation2Size: "",
      underMiningLocation2To: "",
      woundDepth: "",
      woundDescriptionBeefyRed: "",
      woundDescriptionBlackEschar: "",
      woundDescriptionDullPink: "",
      woundDescriptionWhite: "",
      woundExudate: "",
      woundLength: "",
      woundWidth: "",
    },
    {
      volume: "160",
      evaluationDate: "2023-03-27T00:00:00",
      status: "",
      color: "",
      assessmentType: "MWP",
      volumeDifference: -6,
      boneExposed: "",
      comorbidities: [],
      cycleDateRangeFrom: "",
      cycleDateRangeTo: "",
      debridementDate: "",
      debridementDone: "",
      debridementType: "",
      exudateAppearance: "",
      holdVacTherapyDate: "",
      isEschar: "",
      isTherapyInUSe: "",
      isTunnelingPresent: "",
      isUnderMiningPresent: "",
      muscelExposed: "",
      otherComorbidities: "",
      subcutaneousTissueExposed: "",
      tissueExposed: "",
      tunnelingLength1: "",
      tunnelingLength2: "",
      tunnelingLocation1: "",
      tunnelingLocation2: "",
      underMiningLocation1From: "",
      underMiningLocation1Size: "",
      underMiningLocation1To: "",
      underMiningLocation2From: "",
      underMiningLocation2Size: "",
      underMiningLocation2To: "",
      woundDepth: "",
      woundDescriptionBeefyRed: "",
      woundDescriptionBlackEschar: "",
      woundDescriptionDullPink: "",
      woundDescriptionWhite: "",
      woundExudate: "",
      woundLength: "",
      woundWidth: "",
    },
  ]),
  initialVolume: "23",
  latestVolume: "-32",
  changeInVolume: "-3",
  daysOnVACTherapy: "2",
};

export const woundAsesmentDetailsSingleAssesment: IWoundDetail = {
  assessments: ([] = [
    {
      volume: "23",
      evaluationDate: "2023-05-15T00:00:00",
      status: "",
      color: "",
      assessmentType: "MWP",
      volumeDifference: -6,
      boneExposed: "",
      comorbidities: [],
      cycleDateRangeFrom: "",
      cycleDateRangeTo: "",
      debridementDate: "",
      debridementDone: "",
      debridementType: "",
      exudateAppearance: "",
      holdVacTherapyDate: "",
      isEschar: "",
      isTherapyInUSe: "",
      isTunnelingPresent: "",
      isUnderMiningPresent: "",
      muscelExposed: "",
      otherComorbidities: "",
      subcutaneousTissueExposed: "",
      tissueExposed: "",
      tunnelingLength1: "",
      tunnelingLength2: "",
      tunnelingLocation1: "",
      tunnelingLocation2: "",
      underMiningLocation1From: "",
      underMiningLocation1Size: "",
      underMiningLocation1To: "",
      underMiningLocation2From: "",
      underMiningLocation2Size: "",
      underMiningLocation2To: "",
      woundDepth: "",
      woundDescriptionBeefyRed: "",
      woundDescriptionBlackEschar: "",
      woundDescriptionDullPink: "",
      woundDescriptionWhite: "",
      woundExudate: "",
      woundLength: "",
      woundWidth: "",
    },
  ]),
  initialVolume: "23",
  latestVolume: "",
  changeInVolume: "",
  daysOnVACTherapy: "2",
};
export const woundDetailInfo: any = {};
export const assesmentListData: IWoundAssesmentsMap[] = [
  {
    evaluationDate: "2023-04-17T00:00:00",
    Volume: "73",
  },
  {
    evaluationDate: "2023-04-17T00:00:00",
    Volume: "73",
  },
];
