export const DepartmentMock = [
  "Administration",
  "Biomedical",
  "Burn Unit",
  "Critical Care Unit",
  "Critical Intensive Care Unit",
  "Central Processing Department",
  "Cardiothoracic Intensive Care Unit",
  "Cardiology",
  "Case Management",
  "Central Supply",
  "Customer Service",
  "DME Supplier",
  "Discharge Planning",
  "Distribution",
  "Emergency Department",
  "HHA - Home Health Agency",
  "ICU - Intensive Care Unit",
  "Logistics",
  "Medical Intensive Care Unit",
  "Materials Management",
  "Med Engineering",
  "Neonatal Intensive Care Unit",
  "Neuro Trauma",
  "Nursing",
  "Operating Room",
  "Oncology",
  "Orthopedics",
  "PACU",
  "Progressive Care Unit",
  "PICU",
  "Physical Therapy",
  "Physician Office",
  "Prosthetics",
  "Purchasing",
  "Receiving",
  "Rehab",
  "SICU",
  "SNF - Skilled Nursing Facility",
  "STICU",
  "Social Services",
  "Surgical",
  "TICU - Trauma Intensive Care Unit",
  "Trauma",
  "Wound Care Center",
  "Other",
];
