export const INVENTORY_MENU = "INVENTORY";
export const ADMIN_MENU = "ADMINISTRATIVE_SETTINGS";
export const USER_ROLE_CLINICIAN = "CLINICIAN";
export const USER_ROLE_3M_ADMIN = "3M ADMIN";
export const USER_ROLE_FACILITY_ADMIN = "FACILITY ADMIN";
export const USER_ROLE_BASE = "BASEUSER";

